export const changeTheme = (primaryTheme : boolean, setPrimaryTheme : Function)=> {
    const body = document.querySelector('.body')
    const btnTheme = document.querySelector('.btnTheme')
    const container = document.querySelector('.container')
    const title = document.querySelector('.title')
    const inputTask = document.querySelector('.inputTask')
    const btnTask = document.querySelector('.btnTask')
    const btnClear = document.querySelector('.btnClear')
    const task = document.querySelectorAll('.task')
    const btnEdit = document.querySelectorAll('.btnEdit')
    const btnDelete = document.querySelectorAll('.btnDelete')

    if (primaryTheme) {
      body?.classList.add('secondaryTheme-primaryColor')
      body?.classList.remove('mainTheme-primaryColor')
      btnTheme?.classList.add('secondaryTheme-btnTheme')
      btnTheme?.classList.remove('mainTheme-btnTheme')
      container?.classList.add('secondaryTheme-secondaryColor')
      container?.classList.remove('mainTheme-secondaryColor')
      title?.classList.add('secondaryTheme-terciaryColor')
      title?.classList.remove('mainTheme-terciaryColor')
      inputTask?.classList.add('secondaryTheme-mainBorder')
      inputTask?.classList.add('secondaryTheme-inputTask')
      inputTask?.classList.remove('mainTheme-mainBorder')
      inputTask?.classList.remove('mainTheme-inputTask')
      btnTask?.classList.add('secondaryTheme-mainBorder')
      btnTask?.classList.add('secondaryTheme-btnTask')
      btnTask?.classList.remove('mainTheme-mainBorder')
      btnTask?.classList.remove('mainTheme-btnTask')
      btnClear?.classList.add('secondaryTheme-mainBorder')
      btnClear?.classList.add('secondaryTheme-btnClear')
      btnClear?.classList.remove('mainTheme-mainBorder')
      btnClear?.classList.remove('mainTheme-btnClear')
      task.forEach(elem=>{
        elem?.classList.add('secondaryTheme-mainBorder')
        elem?.classList.add('secondaryTheme-task')
        elem?.classList.remove('mainTheme-mainBorder')
        elem?.classList.remove('mainTheme-task')
      })
      btnEdit.forEach(elem=>{
        elem?.classList.add('secondaryTheme-btns-task')
        elem?.classList.remove('mainTheme-btns-task')
      })
      btnDelete.forEach(elem=>{
        elem?.classList.add('secondaryTheme-btns-task')
        elem?.classList.remove('mainTheme-btns-task')
      })
    } else {
      body?.classList.add('mainTheme-primaryColor')
      body?.classList.remove('secondaryTheme-primaryColor')
      btnTheme?.classList.add('mainTheme-btnTheme')
      btnTheme?.classList.remove('secondaryTheme-btnTheme')
      container?.classList.add('mainTheme-secondaryColor')
      container?.classList.remove('secondaryTheme-secondaryColor')
      title?.classList.add('mainTheme-terciaryColor')
      title?.classList.remove('secondaryTheme-terciaryColor')
      inputTask?.classList.add('mainTheme-mainBorder')
      inputTask?.classList.add('mainTheme-inputTask')
      inputTask?.classList.remove('secondaryTheme-mainBorder')
      inputTask?.classList.remove('secondaryTheme-inputTask')
      btnTask?.classList.add('mainTheme-mainBorder')
      btnTask?.classList.add('mainTheme-btnTask')
      btnTask?.classList.remove('secondaryTheme-mainBorder')
      btnTask?.classList.remove('secondaryTheme-btnTask')
      btnClear?.classList.add('mainTheme-mainBorder')
      btnClear?.classList.add('mainTheme-btnClear')
      btnClear?.classList.remove('secondaryTheme-mainBorder')
      btnClear?.classList.remove('secondaryTheme-btnClear')
      task.forEach(elem=>{
        elem?.classList.add('mainTheme-mainBorder')
        elem?.classList.add('mainTheme-task')
        elem?.classList.remove('secondaryTheme-mainBorder')
        elem?.classList.remove('secondaryTheme-task')
      })
      btnEdit.forEach(elem=>{
        elem?.classList.add('mainTheme-btns-task')
        elem?.classList.remove('secondaryTheme-btns-task')
      })
      btnDelete.forEach(elem=>{
        elem?.classList.add('mainTheme-btns-task')
        elem?.classList.remove('secondaryTheme-btns-task')
      })
    }
    setPrimaryTheme(!primaryTheme)
  }